#!/bin/bash

if [ -f "/tmp/gwen.properties" ]; then 
  export GWEN_PROPERTIES=/tmp/gwen.properties
else 
  export GWEN_PROPERTIES=/opt/gwen-web/gwen.properties
fi

#/features -b -r /reports -p ${GWEN_PROPERTIES}
#/opt/gwen-web/gwen-web-1.0.0-SNAPSHOT/bin/gwen-web $*
ls -la /opt/gwen-web
ls -la /opt/gwen-web/gwen-web-1.2.0-1-g3ae08b8-SNAPSHOT/*
/opt/gwen-web/gwen-web-1.2.0-1-g3ae08b8-SNAPSHOT/bin/gwen-web $*
